name: Download-JSON
on:
  schedule:
    - cron: '0 6,9,12,15,18,21 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  download-json:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          ref: 'github-pages'

      # Download JSON from GOV.UK
      - name: Download JSON from GOV.UK
        uses: carlosperate/download-file-action@v1.0.3
        with:
          file-url: 'https://api.coronavirus.data.gov.uk/v2/data?areaType=overview&metric=cumPeopleVaccinatedFirstDoseByPublishDate&metric=cumPeopleVaccinatedSecondDoseByPublishDate&format=json'
          #file-url: 'https://api.coronavirus.data.gov.uk/v2/data?areaType=overview&metric=cumPeopleVaccinatedFirstDoseByVaccinationDate&metric=cumPeopleVaccinatedSecondDoseByVaccinationDate&format=json'
          #file-url:  'https://api.coronavirus.data.gov.uk/v2/data?areaType=overview&metric=cumPeopleReceivingFirstDose&metric=cumPeopleReceivingSecondDose&format=json'
          file-name: 'data.json'
          location: './json'
      # Add and commit
      - name: Add and Commit
        uses: EndBug/add-and-commit@v6
        with:
          add: './json/data.json'
          author_name: 'Daniel Winfield'
          author_email: daniel.winfield@outlook.com
          branch: 'github-pages'
          message: 'Updating json data file'
